### PR TITLE
Testing PR integration with Jenkins

### PR DESCRIPTION
**Pull request by orviz**

### CODE REVIEW

**Comment by fmarco76** [comment]
I am using travis for codestyle and untitest, although there are not unittests at the moment. Codestyle has no problem using maven. How does jenkins run the test?

**Comment by orviz** [comment]
The codestyle check uses checkstyle plugin for maven, running `mvn checkstyle:check` with the options:

checkstyle.config.location=sun_checks.xml
checkstyle.console=true
checkstyle.failOnViolation=true
checkstyle.violationSeverity=warning

It is actually exiting with 71 errors, most of them DesignForExtension exceptions. You can see the complete list in the console output of jenkins for this execution.

The unit test check is using cobertura.

**Comment by fmarco76** [comment]
I have seen the issue. Currently, sun code style requires all method to be abstract or final if not in abstract class and this is in contrast with the requirements of JPA entities.If I add final to the method I get a lot of warnings. For this reason I have added a file _checkstyle-suppressions.xml_ which is called inside the **check plugin** in the **pom** file.

It seems that your test does not use my pom file or does not recognise what it is inside.

How can fix the problem?

**Comment by orviz** [comment]
I don't know why the pom.xml gets ignored; anyway i've added this parameter to the job configuration and is passing now.

**Comment by fmarco76** [comment]
I have accepted the pull request. In the future I can commit to the master or do I have to use this branch for Jenkins test? Do I need to add a badge for the test?

**Comment by orviz** [comment]
this PR was not meant to be merged, i just used it for testing the integration with jenkins. But no worries, let's try to revert it.

Regarding the workflow, the master is protected so you cannot push directly to the master. Instead, you should work with pull requests that will trigger the jenkins checks the same way travis CI does.

**Pull request merged**
